spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dronefeeder?useSSL=false&createDatabaseIfNotExist=true
    username: seu-usuario
    password: sua-senha
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true