spring:

  config:
  
    import: secrets.properties
  
  application:

    name: drone-feeder

  datasource:

    url: jdbc:mysql://${MYSQL_ROOT_HOST}:3306/${MYSQL_DATABASE}?useSSL=true
    
    username: ${MYSQL_ROOT_USER}
    
    password: ${MYSQL_ROOT_PASSWORD}
    
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
  
    properties:

      hibernate:

        dialect:  org.hibernate.dialect.MySQL5Dialect

    show-sql: true
    
    hibernate:
      
      ddl-auto: update

server:

  port: ${APP_PORT}