version: '3'
services:
  drone-feeder:
    image: drone-feeder/api
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000-8999:8080
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=drone-feeder
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./Docker/volume_mysql:/var/lib/mysql
